### ISSUE TITLE
Feature request: timezone conversion

### ISSUE THREAD

**Issue by feigaoxyz** [deanishe/alfred-convert#10]
Any plans for timezones conversion?

**Comment by deanishe** [comment]
It's not something I'd thought about, no.

The workflow is basically a thin wrapper around [the pint library](https://pint.readthedocs.org/en/0.7.2/systems.html). If pint can be made to understand times and timezones, it should be easy enough to grab a list of timezones and feed them to pint, like the workflow currently does with currencies/exchange rates.

I really don't know if that's possible, however.
