### ISSUE TITLE
Add support for bits and bytes &etc. 

### ISSUE THREAD

**Issue by jamesmartin** [deanishe/alfred-convert#11]
Might be worth having unit definitions for bits/bytes/kilobytes/megabytes/gigabytes etc built in.

Here's a gist of my [unit_definitions.txt](https://gist.github.com/jamesmartin/935b9c89c89413db98204e2e91140ef3) for reference.

What do you think?

P.S. Thanks for the workflow; I use it all the time ⚡

**Comment by deanishe** [comment]
They are already built in (although the short forms — b, kb, gb etc. — are missing).

If you want the short forms, add this to your custom `unit_definitions.txt` file:

```
gb = gigabyte
mb = megabyte
kb = kilobyte

gib = gibibyte
mib = mebibyte
kib = kibibyte
```
