### ISSUE TITLE
Option to exclude unit when copying to clipboard

### ISSUE THREAD

**Issue by lumpysimon** [deanishe/alfred-convert#12]
Great workflow thanks!

In most cases I only need the resulting number, not the unit, after doing a conversion. So would it be possible to add an option to specify that only the number is copied to the clipboard, without the unit?

**Comment by deanishe** [comment]
[Added in v3.0](https://github.com/deanishe/alfred-convert/tree/v3.0)

**Comment by lumpysimon** [comment]
Thank you :)
