### ISSUE TITLE
Include pint's spectroscopy (and other context) option(s)

### ISSUE THREAD

**Issue by jmason86** [deanishe/alfred-convert#18]
Great tool! It would be really nice to also take advantage of the more advanced conversions already available in pint, such as converting between energy and length in the context of spectroscopy (e.g., 1 Å = 12398 eV for light).

**Comment by deanishe** [comment]
I'm afraid that means nothing to me. Are you talking about a new version of `pint`?

**Comment by jmason86** [comment]
In the [Pint default definition file](https://github.com/hgrecco/pint/blob/master/pint/default_en.txt) that you linked to in the description, is this code: 
`@context(n=1) spectroscopy = sp
    # n index of refraction of the medium.
    [length] <-> [frequency]: speed_of_light / n / value
    [frequency] -> [energy]: planck_constant * value
    [energy] -> [frequency]: value / planck_constant
    # allow wavenumber / kayser
    1 / [length] <-> [length]: 1 / value
@end
`
I tried conv sp in alfred, but it insists that the first input be a number. I also tried a direct conversion between energy and length (eV to angstrom) but it gave an error that the units didn't make sense.

**Comment by deanishe** [comment]
Right, I've got you. Contexts are not currently supported.

I'm afraid this is over my head mathematically speaking. Could you give me a couple of examples of conversions that should work (`sp 1Å ev` -> `12398 eV` perhaps?), and I'll adjust the parser to allow a context as the first argument.

**Comment by jmason86** [comment]
Awesome thanks! 
More examples would be 
`sp 54 Å eV`-> `229.60 eV` 
`sp 30 keV Å` -> `0.4132 Å`
`sp 0.5 keV nm` -> `2.4796 nm`

**Comment by deanishe** [comment]
Finally added in [v3.2](https://github.com/deanishe/alfred-convert/tree/v3.2).
