### ISSUE TITLE
CPU spikes to 100% 

### ISSUE THREAD

**Issue by garyking** [deanishe/alfred-convert#19]
After running a conversion, the CPU of the Python process spikes to 100% and stays there indefinitely on my Mac. This occurs after any conversion, like currency, or length. 

I think this only started happening a few days ago. I already re-installed the workflow.

**Comment by deanishe** [comment]
Are you running 10.12.4?

If so, [run this workflow](https://github.com/deanishe/alfred-fixum).

**Comment by michaellopez** [comment]
@deanishe Thanks, I had this problem too. Running 10.12.4. Fixum fixed it for me 👍
