### ISSUE TITLE
Any way to add live cryptocurrency data?

### ISSUE THREAD

**Issue by mrbromely** [deanishe/alfred-convert#21]

**Comment by deanishe** [comment]
Bitcoin is already supported.

**Comment by mrbromely** [comment]
Hi,

I saw that it supports BTC and it inspired my thinking that it would be amazing if it could, pull all 'alt' coin prices from a live market like kraken. I think they have a price feed api.

Amazing Alfred extensions thank you so much for sharing!

Martyn

**Comment by deanishe** [comment]
Kraken's not a great fit, as the API is quite complicated to use (presumably because you can also use it to perform trades).

[CryptoCompare](https://www.cryptocompare.com/api/) looks like a good fit, though.

I'll look into it.

**Comment by mrbromely** [comment]
CryptoCompare would be amazing! I use it for portfolio tracking didn't even think about them having a feed, I'm not able to code but more than happy to help test or work through any flows if you get round to making it work.

**Comment by deanishe** [comment]
I've added support for (most of) the currencies supported by CryptoCompare, but there are a stupid number of them (>1000). I'd prefer not to include them all for reasons of performance (downloading and registering them) and clarity (I'd rather not have hundreds of "meaningless" currencies in the currency list).

Do you have any idea which ones actually matter?

**Comment by mrbromely** [comment]
True, there are a huge ammount of s**t coins out there, perhaps limit it to the top 100 coins (https://coinmarketcap.com/) for now. Obviously this changes pretty quickly these days so if there is an easy way for users to add other desired coins then that would be super amazing.

**Comment by deanishe** [comment]
[Added in v3.0](https://github.com/deanishe/alfred-convert/tree/v3.0)

By default, I've only activated a handful of cryptocurrencies. Use `convinfo` then `Edit Active Currencies` to add the desired symbols to the list of active currencies.

**Comment by mrbromely** [comment]
Fantastic! Thanks for all you effort on this hopefully it will be useful for others as well.
