### ISSUE TITLE
Unknown unit: XRP

### ISSUE THREAD

**Issue by jukben** [deanishe/alfred-convert#22]
This should work since version 3.0, right? 

**Problem:** XRP unit (Ripple coin) is not recognized. 
**Steps to reproduce:** try to convert 1 XRP to another currency, for example, USD 
**Expected behavior:** Should print converted amount (like in the case of BTC)

<img width="572" alt="screen shot 2017-07-17 at 16 09 18" src="https://user-images.githubusercontent.com/8135252/28271950-5a19443a-6b0a-11e7-9461-509fd9b0fdd8.png">
<img width="575" alt="screen shot 2017-07-17 at 16 14 09" src="https://user-images.githubusercontent.com/8135252/28272189-fff3e8ec-6b0a-11e7-8547-3d62b95c0641.png">

**Comment by deanishe** [comment]
It works for me…

Do any currency conversions work? If you machine is offline, it won't be able to get any exchange rates, so no currencies will be loaded.

If you run `convinfo` and then `Edit Active Currencies`, is `XRP` in the list?

Try `conv workflow:openlog`. Are there any error messages in the log? (This is *not* the same as Alfred's debugger.)

**Comment by jukben** [comment]
Yeah, there are a lot of cryptocurrencies in the active_currencies.txt but the problem is same with other of them. So it has to be something general. See the log below.

```17:07:25 convert.py:294 CRITICAL invalid query (1 ZEC): Unknown unit: ZEC
17:07:26 convert.py:294 CRITICAL invalid query (1 ZEC ): Unknown unit: ZEC
17:07:28 convert.py:294 CRITICAL invalid query (1 ): No units specified
17:07:31 convert.py:294 CRITICAL invalid query (1 AUR ): Unknown unit: AUR
17:07:33 convert.py:294 CRITICAL invalid query (1 AUR CZK): Unknown unit: AUR
17:07:36 convert.py:294 CRITICAL invalid query (1 BUT): Unknown unit: BUT
17:07:37 convert.py:302 CRITICAL No to_units (or defaults) for dimensionless
17:07:38 convert.py:302 CRITICAL No to_units (or defaults) for [currency]
17:07:39 convert.py:294 CRITICAL invalid query (1 ): No units specified
17:07:42 convert.py:294 CRITICAL invalid query (1 ETC ): Unknown unit: ETC
17:08:02 convert.py:294 CRITICAL invalid query (!): Start your query with a number
17:08:03 convert.py:294 CRITICAL invalid query (1 XRP c): Unknown unit: XRP
17:08:04 convert.py:294 CRITICAL invalid query (1 XRP ): Unknown unit: XRP
17:08:05 convert.py:294 CRITICAL invalid query (1 XRP CZK): Unknown unit: XRP
17:08:20 convert.py:294 CRITICAL invalid query (1 ): No units specified
17:08:23 convert.py:294 CRITICAL invalid query (1 DOGE ): Unknown unit: DOGE
17:08:24 convert.py:294 CRITICAL invalid query (1 DOGE c): Unknown unit: DOGE
17:08:25 convert.py:294 CRITICAL invalid query (1 DOGE czk): Unknown unit: DOGE
17:11:11 convert.py:294 CRITICAL invalid query (workflow:openlo): Start your query with a ```

**Comment by deanishe** [comment]
Most likely updating the exchange rates failed. It's possible that cryptocompare.com was temporarily unavailable.

Try `conv workflow:delcache` to remove any cached exchange rates, try another conversion (which will trigger an update), then check the log file for messages relating to updating the exchange rates.

**Comment by jukben** [comment]
Yeah, you are probably right, after `conv workflow:delcache` it's working now properly. Thanks for this piece of software. 👍

**Comment by deanishe** [comment]
> Data source is temporarily unavailable

Thinking about it, the issue probably wasn't that the workflow couldn't connect to the service, but rather that an update of exchange rates simply wasn't due for a few hours. You were still working with data from v2, which doesn't support any cryptocurrencies except Bitcoin.

The only time you'll ever have this issue is the first time you install v3.0 and after adding new active currencies.

I'll add a command to manually force an update of the exchange rates.

**Comment by jukben** [comment]
@deanishe `The only time you'll ever have this issue is the first time you install v3.0 and after adding new active currencies.` Yeah, that's was actually my case. The readme will be great. Thanks again! 👍
