### ISSUE TITLE
Some cryptos giving "unknown unit" error, while being listed in alfred-convert/currencies/currencies_crypto.tsv

### ISSUE THREAD

**Issue by benwoodward** [deanishe/alfred-convert#24]
![image](https://user-images.githubusercontent.com/1472981/28314086-89645430-6bfc-11e7-8207-176d4fd86434.png)

![image](https://user-images.githubusercontent.com/1472981/28314125-abd8604c-6bfc-11e7-9e1e-ccb92379eec7.png)

Using v3.0 of alfred-convert and v3.4 [850] of Alfred.

**Comment by deanishe** [comment]
See #22 

Most likely the same issue.

**Comment by benwoodward** [comment]
Thanks.
