### ISSUE TITLE
Area conversion error

### ISSUE THREAD

**Issue by trevorh** [deanishe/alfred-convert#25]
Hi,

I was attempting a unit conversion and this works:

`conv 10 m**2 sq_in` which displays 15,500.03

but if you reverse it

`conv 10 sq_in m**2` you get an error saying `'ascii' codec can't encode character 'u\xb2' in position 5: ordinal not in range(128)`

Should I be using another unit name instead of m**2? The same thing happens if I use m^2.

Thanks!

**Comment by deanishe** [comment]
> Should I be using another unit name instead of m**2

Nope. It was a bug. I've fixed it in [v3.0.1](https://github.com/deanishe/alfred-convert/releases/tag/v3.0.1). Grab it from the link of enter `conv workflow:update` to grab it directly from Alfred.

Sorry about that, and thanks for finding the bug.

**Comment by trevorh** [comment]
No problem! I really appreciate you fixing it so quickly.
