### ISSUE TITLE
Updating exchange rates

### ISSUE THREAD

**Issue by heihachi88** [deanishe/alfred-convert#27]
These days i've noticed the following bug:

When i type `conv 1 usd kzt` it keeps telling my "Updating exchange rates" and i won't get actual data...

**Comment by deanishe** [comment]
What does the log file say? (Enter `conv workflow:openlog` to see it.)

**Comment by deanishe** [comment]
It appears that the Yahoo! Finance API is no more. I've replaced it with [openexchangerates.org](https://openexchangerates.org) in [v3.1](https://github.com/deanishe/alfred-convert/tree/v3.1).

You'll need an API key, which you can get for free [here](https://openexchangerates.org/signup/free).

**Comment by heihachi88** [comment]
Wait, how to update to 3.1? Cryptocurrencies are available without yahoo?

**Comment by deanishe** [comment]
> Where to put API key?

[Read the instructions](https://github.com/deanishe/alfred-convert#configuration)

>  this project shows wrong currency prices...

For example…?

> Also it doesn't know Kazakhstani tenge

Yes, it does.

> Possible to use: https://finance.google.com/finance?

I already told you "no".

**Comment by tenpoundhero** [comment]
@deanishe Do you just copy and paste the entire result generated from the api key request into "value" for APP_KEY? I've done that so far and it's still not working correctly for me.

**Comment by deanishe** [comment]
@tenpoundhero When you sign up, they send you an email with an "App ID". Paste that in to the `APP_KEY` value.

**Comment by tenpoundhero** [comment]
@deanishe `APP_KEY`now has my "App ID" 

`
18:23:08 convert.py:323 CRITICAL No to_units (or defaults) for [currency]
18:23:09 convert.py:323 CRITICAL No to_units (or defaults) for [currency]
18:23:10 convert.py:315 CRITICAL invalid query (1usd gbp): Unknown unit: gbp
18:23:21 convert.py:323 CRITICAL No to_units (or defaults) for [currency]
18:23:22 convert.py:315 CRITICAL invalid query (1 usd gbp): Unknown unit: gbp
`

That's my log, it's still having trouble finding GBP

**Comment by deanishe** [comment]
Can you post the entire log for that query (i.e. not just the error message) and format it properly, please?

Also, try running `conv workflow:delcache` first.

**Comment by tenpoundhero** [comment]
Well I cleared the cache and that seems to for some reason fixed the issue...

Thanks for the help!

**Comment by heihachi88** [comment]
> this project shows wrong currency prices...

`conv 1btc usd` shows 7.183USD, while everywhere it's 7.238USD. Where does (openexchangerates.org) gets cryptocurrency rates?

**Comment by heihachi88** [comment]
How to refresh rates quickly?

**Comment by deanishe** [comment]
I see you still haven't read the README.

Please stop wasting my time with questions that are answered in the README.
