### ISSUE TITLE
Currency converter broken

### ISSUE THREAD

**Issue by NickAnderegg** [deanishe/alfred-convert#29]
I'm suddenly not able to do all the currency conversions I'm used it. I've used the currency converter several times a day for years now, and it's suddenly failing to recognize my most used conversion, USD to CAD.

![image](https://user-images.githubusercontent.com/542937/32400754-90f4163a-c0da-11e7-819e-4ef9f13e5d47.png)

![image](https://user-images.githubusercontent.com/542937/32400763-9ff28c66-c0da-11e7-9412-e9511ba3edd4.png)

**Comment by madsb** [comment]
Many cryptocurrencies are also broken.

**Comment by deanishe** [comment]
Not the same problem as the last issue? #28

**Comment by madsb** [comment]
Adding the APP_KEY fixed it for me - thanks!

**Comment by NickAnderegg** [comment]
Yup, I missed that issue. It might be helpful to have a notice or something when someone tries a conversion with the new version, because I'm guessing not everyone will check GitHub!

**Comment by deanishe** [comment]
> It might be helpful to have a notice or something

I’ve thought about how best to do that. The way the workflow is currently built means it doesn’t know any currencies until they’re loaded from the cache … which doesn’t exist until `APP_KEY` is set.

Maybe add some extra logic to the “unknown unit” error that checks it against the currency list, and shows a different notice if the unit is a currency.

**Comment by NickAnderegg** [comment]
You could probably get away with hard coding a list of just a handful of the most common currencies to catch >95% of users. Like there's probably not a huge contingent of users who are converting New Zealand Dollars into Swiss Francs or South African Rand into Indian Rupees.

It'll probably be fine to just check something like:

- USD
- CAD
- GBP
- EUR
- AUD
- JPY
- CNY

I'd best the *majority* of exchange rate looks up will involve at least one of those currencies and cover most users.

**Comment by deanishe** [comment]
> the most common currencies

I don’t think that would work: the workflow short circuits to failure if the first currency isn’t recognised.

It’s not a big deal: it already contains a list of all currencies, they just aren’t fed into the conversion library unless an exchange rate is available.
