### ISSUE TITLE
Feature Request: Parse value in respect to delimiters in configs

### ISSUE THREAD

**Issue by eppfel** [deanishe/alfred-convert#31]
Awesome workflow!

It's neat, that you can set different delimiters for the results, but I expected the configurations also to affect the input. 

https://github.com/deanishe/alfred-convert/blob/76be62d7e877d5829bbce11e0ab43ca0200451c8/src/convert.py#L277
I unsuccessfully tried using the `Formatter` on that value, but I don't know much about python. Guess it would need some conversion.

A nice solution would parse the number no matter what:

```
23.34 => 23.34
23,34 => 23.34
12.123,345 => 12123.345
12,123.345 => 12123.345
```

The only problem would be three decimal places:
`23,345 => 23.345 / 23345.00 ???`

And this does not considers all cases.

So using the configuration would be most convenient, I guess.

**Comment by deanishe** [comment]
Added in [v3.3](https://github.com/deanishe/alfred-convert/releases/tag/v3.3).

Numbers will now be parsed in accordance with the separators you've set in the configuration sheet.

**Comment by eppfel** [comment]
Works like a charm :+1:
