### ISSUE TITLE
CRC is being used for 2 currencies 

### ISSUE THREAD

**Issue by harroyoc** [deanishe/alfred-convert#32]
Costa Rican Colon (CRC) exchange rate is either completely off, or the workflow is using the CraftCoin (also CRC) currency when converting to CRC.

![crc](https://user-images.githubusercontent.com/2280829/33046312-116a710e-ce16-11e7-97a2-c9e57f6b27de.png)

**Comment by deanishe** [comment]
> the workflow is using the CraftCoin (also CRC) currency when converting to CRC

That's exactly what's happening.

It looks like quite a few cryptocurrencies duplicate the symbols of fiat currencies.

For the time being, I've disabled conflicting currencies (mostly the crypto ones).

Grab [v3.3.1](https://github.com/deanishe/alfred-convert/releases/tag/v3.3.1) from releases or enter `conv workflow:update` into Alfred.

Enter `conv workflow:delcache` if you'd like to force exchange rates to be updated immediately (the bad data will still be in the cache).

**Comment by rwitchell** [comment]
is it possible that you modify the plugin to output multiple results, one for each currency?

**Comment by deanishe** [comment]
> is it possible that you modify the plugin to output multiple results, one for each currency?

No, I'm afraid not. The `pint` library (perfectly understandably) expects a name to refer to a single unit only.

It might be possible if the conflicting units weren't both currencies, but if the creators of CraftCoin (and the rest) were silly enough to use a code that's already assigned to a different currency, then it was bound to cause some issues…

If you'd rather have CraftCoin than the Costa Rican colon, you can uncomment the former and comment out the latter [in `config.py`](https://github.com/deanishe/alfred-convert/blob/master/src/config.py#L58).

The only currencies that are fundamentally unsupported are ones whose currency codes begin with digits.

I'm closing this issue, as I've solved the issue, albeit by removing some currencies.
