### ISSUE TITLE
How to edit "configuration sheet"

### ISSUE THREAD

**Issue by ryqiem** [deanishe/alfred-convert#33]
The help-guide wasn't very useful for me in trying to add the APP_KEY from Open Exchange Rates – I ended up opening the workflow and editing the .plist.

Clarification would be super helpful! :-)

Thanks!

**Comment by deanishe** [comment]
Open the workflow in Alfred Preferences and click the `[𝒙]` button.

See section **Setting Workflow Environment Variables** of [Alfred's help](https://www.alfredapp.com/help/workflows/advanced/variables/).

I take your point about clarification, but we're in the territory of fairly basic Alfred usage here.

**Comment by ryqiem** [comment]
Haha, thanks! The addition of "open the workflow in Alfred preferences" clarified it enough that I could find it.

I consider myself a rather heavy user of workflows (about 15 workflows active, 3 of which I've done myself), and this is the first time I'm messing around with env. variables manually.

Thanks for an awesome workflow, and thank you for taking the time to answer my question 👍

**Comment by chusiang** [comment]
1. Get the **App_ID** from https://openexchangerates.org/ .

    > Please reference the https://github.com/deanishe/alfred-convert#configuration .

2. Enter the **Workflows**.
3. Enter the **Convert**.
4. Click the **[X]** button.
5. Paste the myself **App_ID** into **Value** field. 

    ![2017-11-28-convert-configuration-sheet](https://user-images.githubusercontent.com/219066/33302204-89bceea0-d435-11e7-80e5-ec8cd020a859.png)

Enjoy. :sunglasses:

**Comment by ryqiem** [comment]
I suggest copying @chusiang's addition to the help file and marking this as solved 😉

**Comment by deanishe** [comment]
> The addition of "open the workflow in Alfred preferences"

The first line of the **Configuration** section reads:

> The workflow is configured via the configuration sheet (`[𝓍]`) in Alfred Preferences

There are also links to the sign-up and API page in the **Conversions** section.

> I suggest copying @chusiang's addition to the help file

I'm not going to add a screenshot of Alfred Preferences to the README. This is the standard way to configure Alfred 3 workflows.

It's basic usage for Alfred Powerpack owners, not something that should need explaining in a workflow README.
