### ISSUE TITLE
Unknown unit ?

### ISSUE THREAD

**Issue by ryanmclaughlin** [deanishe/alfred-convert#39]
Hi there,

Every conversion I try, I get an 'unknown unit' error.
![image](https://user-images.githubusercontent.com/451112/34975631-5db212b0-fa58-11e7-95b6-8a07deff8818.png)

**Comment by jostyee** [comment]
Have you set your API key?

**Comment by ryanmclaughlin** [comment]
No, I have not. I didn't realize I needed to do that. What do I need to do
for crypto and fiat?

**Comment by ryanmclaughlin** [comment]
Apologies. I have no idea how I missed that in the docs. Swear I read it. Thanks!

**Comment by ryanmclaughlin** [comment]
@jostyee Okay, I've signed up and set it in the config sheet. Unfortunately not working still.

**Comment by jostyee** [comment]
I have no idea, maybe you have to check the extension's log.

**Comment by deanishe** [comment]
Try entering `conv workflow:delcache` to clear any cached data, then try again.

**Comment by deanishe** [comment]
I presume that worked. Closing the issue.
