### ISSUE TITLE
How to add the API key?

### ISSUE THREAD

**Issue by claudioruiz** [deanishe/alfred-convert#40]
This may sound quite stupid, but I'm staring at the documentation without understanding how do I add the openexchangerates API key I just created to the extension.

Do I need to edit manually the extension files? How so? thanks!

**Comment by jimmykl** [comment]
![image](https://user-images.githubusercontent.com/113574/35156490-dd326fea-fd95-11e7-9019-d71643e89e19.png)

![image](https://user-images.githubusercontent.com/113574/35156551-08b2ac0c-fd96-11e7-888e-9c3ea9da7096.png)

**Comment by claudioruiz** [comment]
Thanks for that!
