### ISSUE TITLE
Confusion with Plank's constant

### ISSUE THREAD

**Issue by mkxml** [deanishe/alfred-convert#41]
Hello.

Great workflow. I noticed that I can't currently convert between km/h or mi/h and another unit of speed.

In my country `kph` is not common, we use `km/h` all the time.

I noticed the workflow is confusing this notation with a division involving the `plank_constant`.

It works if I use `conv 32km/hour mi/hour`.

Also can't do, for example,  `conv 5760h min`.

In some cases, should `h` just be mapped to 1 hour?

Should we change this behavior or keep it? What do you think?

**Comment by deanishe** [comment]
> In some cases, should h just be mapped to 1 hour?

Arguably, but [Pint](https://github.com/hgrecco/pint) doesn't work that way. AFAIK, a name, like `h`, can only refer to one unit. That would have to be changed in Pint.

If you don't care about Planck's constant, you can [redefine hour to include `h` as an alias](https://github.com/deanishe/alfred-convert#adding-custom-units), or you can use [`km/hr`](https://github.com/hgrecco/pint/blob/master/pint/default_en.txt) instead.
