### ISSUE TITLE
Can't convert ZCL (cryptocurrency)

### ISSUE THREAD

**Issue by jimmykl** [deanishe/alfred-convert#42]
I can convert some cryptocurrencies e.g. ```conv 1 btc usd``` & ```conv 1 zec usd``` work but not ZCL (zclassic) e.g. ```conv 1 zcl usd``` returns ```Unknown unit zcl```

ZCL is listed in https://github.com/deanishe/alfred-convert/blob/master/docs/currencies.md#cryptocurrencies and present on https://www.cryptocompare.com/coins/zcl/overview

**Comment by deanishe** [comment]
[Only a handful of cryptocurrencies are active by default](https://github.com/deanishe/alfred-convert#active-currencies) to avoid unnecessary load on the CryptoCompare servers.

Enter `convinfo > Edit Active Currencies` in Alfred and add ZCL to the list.

**Comment by jimmykl** [comment]
Great thanks!
