### ISSUE TITLE
"Configuration Sheet" - where is it?

### ISSUE THREAD

**Issue by wabiloo** [deanishe/alfred-convert#43]
The documentation mentions a configuration sheet in which APP_KEY (for currency conversion) should be added. Where is that configuration sheet?  An enigmatic [x] is all that can be found in the documentation...

**Comment by deanishe** [comment]
> An enigmatic [x] is all that can be found in the documentation...

Because [that's the icon for the configuration sheet](https://www.alfredapp.com/help/workflows/advanced/variables/#environment).

**Comment by deanishe** [comment]
I've clarified the README (again) to better explain where the configuration sheet is.
