### ISSUE TITLE
Feature Request: Period to Frequency

### ISSUE THREAD

**Issue by xhain** [deanishe/alfred-convert#45]
As a user of the convert alfred workflow I want to be able to convert from frequency (Hz) to a period back and forth.

// Period (T) to Frequency (Hz)

Input: conv 5 s Hz
Output: 0.2 Hz

Input: conv 0.25 s Hz
Output: 4 Hz

Input: conv 1 ms Hz
Output: 1000 Hz

// Frequency (Hz) to Period (T)

Input: conv 1000 Hz ms
Output: 1 ms

**Comment by deanishe** [comment]
You need to define a [Pint context](http://pint.readthedocs.io/en/0.7.2/contexts.html) in the [custom definitions file](https://github.com/deanishe/alfred-convert/blob/master/README.md#adding-custom-units).

Then you can use the context in conversions, as [described in the README](https://github.com/deanishe/alfred-convert/blob/master/README.md#conversions).
