### ISSUE TITLE
Feature request: conversion between millimeter and pixel

### ISSUE THREAD

**Issue by itamud** [deanishe/alfred-convert#46]
When I hit `conv 170 mm pixel`, it says `Can't convert from millimeter [length] to pixel [printing_unit]`

Then I found a formula to convert between millimeter and pixel at the bottom of [this page](https://www.unitconverters.net/typography/millimeter-to-pixel-x.htm), and it works perfectly for me.

So, why not add this functionality into alfred-convert?

**Comment by deanishe** [comment]
You *can't* convert from mm to pixels because a pixel doesn't have a defined physical size. That depends on the density of the display.
