### ISSUE TITLE
Base conversion

### ISSUE THREAD

**Issue by GIPdA** [deanishe/alfred-convert#48]
Hi,
Would it be possible to convert between number bases? I'm thinking of decimal, hexadecimal, binary, etc, for "coding" purposes.
I looked at the default units and Pint docs, but I couldn't find anything about that. Is it possible to add a unit that call a python function maybe?
Thanks

**Comment by deanishe** [comment]
Nope, afraid not. As you note, Pint doesn't support bases, and I do not plan to make the workflow anything more than an Alfred frontend to Pint.
