### ISSUE TITLE
Feature request: Copy without separator

### ISSUE THREAD

**Issue by lewisthompson** [deanishe/alfred-convert#50]
`conv 1hr s` shows `3,600 second` in the UI and copies `3,600` to the clipboard.

I like that the UI shows the thousand groupings, however, often I'm converting units for programming, spreadsheets, etc. and in those situations I usually want the "raw" value.

An option to show the thousand separators in the UI but not copy them to the clipboard would be great.  Final result would be:

`conv 1hr s` shows `3,600 second` in the UI and copies `3600` to the clipboard.

**Comment by deanishe** [comment]
Uh, scratch that. I just checked Alfred's built-in calculator and it does the opposite (`↩` copies the result without thousands separator).

[v3.5.3](https://github.com/deanishe/alfred-convert/releases/tag/v3.5.3) behaves the same as Alfred.
