### ISSUE TITLE
Feature Request: Make destination unit optional and just return list of converted destinations

### ISSUE THREAD

**Issue by joihelgi** [deanishe/alfred-convert#52]
When you do not specify the destination unit you will get a error saying `No destination units (or defaults) for [dimensionality]`.

<img width="581" alt="Screenshot 2019-05-15 at 18 19 49" src="https://user-images.githubusercontent.com/2881013/57799837-7ae53f00-773f-11e9-8f0d-587546c084d4.png">

It would be nice to get instead a list of converted destinations similar how Spotlight guesses your "to unit":

<img width="678" alt="Screenshot 2019-05-15 at 18 21 04" src="https://user-images.githubusercontent.com/2881013/57799832-791b7b80-773f-11e9-8f22-336f6975bae2.png">

**Comment by deanishe** [comment]
You can use `⌘↩` to save a unit as a default.

If you've set some defaults, the workflow will show those conversions when there isn't a destination unit.

![image](https://user-images.githubusercontent.com/747913/57913958-040a8c00-788e-11e9-91d0-b8b2c8af7ee8.png)
