### ISSUE TITLE
The temperature conversation doesn't work with ° symbol

### ISSUE THREAD

**Issue by FMeilleur** [deanishe/alfred-convert#54]
Converting temperature using the '°' symbol isn't recognized. Using 'deg' or 'degree' does work thou.
<img width="650" alt="Capture d’écran, le 2019-07-04 à 20 35 33" src="https://user-images.githubusercontent.com/52551710/60691129-85989680-9e9b-11e9-8d34-2e4bab622b1f.png">
<img width="650" alt="Capture d’écran, le 2019-07-04 à 20 35 48" src="https://user-images.githubusercontent.com/52551710/60691132-892c1d80-9e9b-11e9-85cf-4c74415366d1.png">

Is there an easy way to edit the basic units to make it work ?

Thanks

**Comment by deanishe** [comment]
> Is there an easy way to edit the basic units to make it work ?

Not that I know of. This is a question for [the `pint` folks](https://github.com/hgrecco/pint), which is responsible for parsing units and performing the conversions.
