### ISSUE TITLE
Having more than one convert result as defaults

### ISSUE THREAD

**Issue by robot110011** [deanishe/alfred-convert#58]
Is it possible to change that to have like the spotlight results like below?
![Screen Shot 2019-09-25 at 23 11 07](https://user-images.githubusercontent.com/2906581/65640098-dbd42c00-dfe9-11e9-92b8-2f800a3828e9.png)

**Comment by deanishe** [comment]
Yes. You just need to add multiple units using <kbd>⌘↩</kbd>

![image](https://user-images.githubusercontent.com/747913/65642867-9404d300-dff0-11e9-97b9-d06bd2d19744.png)

**Comment by robot110011** [comment]
Thanks!
