### ISSUE TITLE
Integrate bitcoins

### ISSUE THREAD

**Issue by jhein05** [deanishe/alfred-convert#6]
Hi,

could you integrate bitcoins as a currency as they are becoming more and more popular. There is no official ISO code yet, but most widely XBT or BTC are used:
http://www.xe.com/currency/xbt-bitcoin#

That would be awesome :)

**Comment by deanishe** [comment]
Added it [v2.2](https://github.com/deanishe/alfred-convert/releases/tag/v2.2)

**Comment by altern8tif** [comment]
@deanishe Still doesn't work after update though.

![screen shot 2015-07-16 at 11 25 54 am](https://cloud.githubusercontent.com/assets/5793364/8714926/7fb48900-2bad-11e5-8548-8736007c634c.png)

**Comment by deanishe** [comment]
![image](https://cloud.githubusercontent.com/assets/747913/8716912/00cca3aa-2b96-11e5-9608-345e336e69d9.png)

New currencies are only available after the exchange rates have been updated. If they haven't updated yet, enter `conv workflow:delcache` to clear the cached rates, and they'll be updated again the next time you run the workflow.

**Comment by altern8tif** [comment]
@deanishe Aha! Thanks! It works now.
