### ISSUE TITLE
automatic entry of 1 into first currency field

### ISSUE THREAD

**Issue by Baggydawg** [deanishe/alfred-convert#69]
The typical finance terminology for foreign exchange would be: USD GBP

The assumption is obviously that the first currency is set to one, however the workflow requires me to type 1 each time for a conversion.

Would it be possible to update the workflow so it recognises the first item in the currency pair will be set to 1 should the user not specify otherwise?

**Comment by deanishe** [comment]
> The typical finance terminology for foreign exchange would be: USD GBP

This isn't a "currency conversion" workflow, it's a "unit conversion" workflow. Currencies are just another unit, so FOREX conventions aren't really interesting for determining the workflow's behaviour.

**Comment by Baggydawg** [comment]
That's true.

In which case if you wouldn't mind, could you point me to where in the code I could edit it myself?

I'd just add an if statement that passes undefined currency units e.g. 'usd eur' through to the same output as '1 usd eur'.

**Comment by deanishe** [comment]
> I'd just add an if statement that passes undefined currency units e.g. 'usd eur' through to the same output as '1 usd eur'

It doesn't work that way. The input format is `[context] number input-unit [output-unit]`, so you'd need to edit [the query parser](https://github.com/deanishe/alfred-convert/blob/896c145c5364e3acd6edd11d0c32745ba4e65e92/src/convert.py#L355) to catch a `ValueError` from `Converter.parse_context()` and do something like `query = '1 ' + query`.
