### ISSUE TITLE
First conversion example in readme is invalid

### ISSUE THREAD

**Issue by danhstevens** [deanishe/alfred-convert#8]
It reads `conv 128 mph km` which returns an error:

![image](https://cloud.githubusercontent.com/assets/1061040/12332258/0da1bd02-bab3-11e5-987a-606c2ecd40c8.png)

**Comment by deanishe** [comment]
Thanks for noticing that! I've fixed the error.

**Comment by danhstevens** [comment]
Awesome. Thanks!
