### ISSUE TITLE
Not working on OSX 10.11.2

### ISSUE THREAD

**Issue by derekkinsman** [deanishe/alfred-convert#9]
I'm running mid 2014 13" MBP with OSX 10.11.2 and this plugin (downloaded from packal.org) is no longer functioning. I've attached a screenshot. It just sits in this mode and never does anything.

<img width="654" alt="screen shot 2016-01-27 at 2 14 17 pm" src="https://cloud.githubusercontent.com/assets/611218/12625118/4e28ba18-c500-11e5-91df-ce007bde1070.png">

**Comment by deanishe** [comment]
The workflow runs just fine on 10.11.2.

Your system Python is probably messed up. Try running First Aid in Disk Utility.

**Comment by derekkinsman** [comment]
Just reinstalled it again (v2.5) from Packal and everything seems to working again. No idea why. I don't think I was running an earlier version, and I didn't do anything with Python, nor is it messed up. Anyway, I'm closing this issue.
