### ISSUE TITLE
zsh: no such file or directory: /usr/bin/python

### ISSUE THREAD

**Issue by dandro180** [deanishe/alfred-convert#93]
I understand that this issue arises because I attempted to change the default version of python 2.7 (which by the way it says it's not recommended since it is an outdated version) for the latest version of python3. 

Apparently, I can host various versions of python because I brew installed pyenv so I can update the default version to the latest one. This made many modules from the workflow.py disappear and now some of my workflows on Alfred don't work.

I understand python3 is not compatible with the workflow.py module calls. 

Can you please help me to solve this issue? I just need to put back whatever version of python that is compatible with these workflows. 

I am not a python expert and I am afraid that if I do it the wrong way I may screw the OS, so I would be very grateful for your answers.

When I run `/usr/bin/python` on terminal I get this: 

`zsh: no such file or directory: /usr/bin/python`

However, I have not seen any other strange behaviour so far on my OS or the workflows compatible with python3.

Thanks.

**Comment by spirosbax** [comment]
same problem here

**Comment by jlk195** [comment]
same here.. Cant get 'Convert' working again..

**Comment by spirosbax** [comment]
Found the solution here https://github.com/alfredapp/updated-third-party-python2-workflows . Also works for other older workflows that depend on python2.

**Comment by dandro180** [comment]
The problem seems to be caused by the macOS upgrade to Monterey 12.3. I asked the same question on the Alfred Forum and was redirected to this page: https://www.alfredforum.com/topic/17941-making-python-2-workflows-work-on-macos-monterey-123-and-above/

So it redirects to the same GitHub page to retrieve the patched workflows with python2 as the above user has indicated.
